name: Combiner

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Video Url'
        required: true
        default: 'NULL'

jobs:
  CombineAndUpload:
    name: Combine and upload videos
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: docker.pkg.github.com
          username: $GITHUB_ACTOR
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Combine
        uses: nekomiyakumi/ytb-combiner@v0.1
        with:
          bucket: ${{ secrets.BUCKET_NAME }}
          video_url: ${{ github.event.inputs.url }}
        env:
          RCLONE_CONFIG_TARGET_TYPE: b2
          RCLONE_CONFIG_TARGET_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          RCLONE_CONFIG_TARGET_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}