name: Combiner

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Video Url'
        required: true
        default: 'NULL'

jobs:
  CombineAndUpload:
    name: Combine and upload videos
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Release
        uses: andreiio/rclone-release@v2
        with:
          bucket: "s3:release"
          publish_dir: ./public
          release_name: project-name
        env:
          RCLONE_CONFIG_S3_TYPE: s3
          RCLONE_CONFIG_S3_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          RCLONE_CONFIG_S3_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
  
